name: Copy latest artifacts to releases
  
on:
  workflow_dispatch:
  schedule:
    - cron:  '46 3 * * *'

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - name: "Download artifacts"
      run: |
        gh run --repo ${GITHUB_REPOSITORY} download -n 'Focus-stack Mac OS X application'
        gh run --repo ${GITHUB_REPOSITORY} download -n 'Focus-stack Ubuntu 20.04 package'
        gh run --repo ${GITHUB_REPOSITORY} download -n 'Focus-stack Linux x86_64 AppImage'
        gh run --repo ${GITHUB_REPOSITORY} download -n 'Focus-stack Windows binary'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: List artifacts
      run: |
        find
    - uses: pyTooling/Actions/releaser@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: 'nightly'
        files: |
          ./*