name: Windows binary

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_windows:
    name: Build binary on Windows 2022
    runs-on: windows-2022
    env:
      VCPKG_BUILD_TYPE: release
    
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v2
        with:
          path: focus-stack
          fetch-depth: "0"
      
      - name: Set vcpkg build type
        shell: powershell
        working-directory: C:\vcpkg\triplets
        run: |
          $PSDefaultParameterValues['Out-File:Encoding'] = 'utf8'
          echo "set(VCPKG_BUILD_TYPE release)" | Tee-Object -FilePath x64-windows-static.cmake -Append
          echo "set(VCPKG_BUILD_TYPE release)" | Tee-Object -FilePath x64-windows.cmake -Append
          echo "set(VCPKG_BUILD_TYPE release)" | Tee-Object -FilePath x86-windows-static.cmake -Append
          echo "set(VCPKG_BUILD_TYPE release)" | Tee-Object -FilePath x86-windows.cmake -Append
          cat x64-windows-static.cmake
          cat x64-windows.cmake

      - name: Cache dependencies
        id: cache-vcpkg-1
        uses: actions/cache@v2
        with:
          path: |
            C:\Users\runneradmin\AppData\Local\vcpkg\archives
            C:\vcpkg\installed
          key: vcpkg-win2022-cache

      - name: Install OpenCV dependency
        shell: cmd
        run: |
          C:
          cd C:\vcpkg\installed
          tree /F
          vcpkg install opencv:x64-windows
          tree /F
      
      - name: Build binary
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cd focus-stack
          nmake -f Makefile.windows OPENCV_INC=C:\vcpkg\installed\x64-windows\include OPENCV_LIB=C:\vcpkg\installed\x64-windows\lib\opencv*.lib OPENCV_DLL=C:\vcpkg\installed\x64-windows\bin\*.dll
          nmake -f Makefile.windows package
    
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: focus-stack/distrib/*.zip
          name: Focus-stack Windows binary
